# Generated by Django 3.0.7 on 2020-06-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='matching_user_has_only_one_participant',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('is_A', True), ('is_B', True), _negated=True), name='matching_user_has_only_one_participant'),
        ),
    ]
