# Generated by Django 3.0.7 on 2020-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_permission_group_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanta',
            name='max_mails_per_day',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='participantb',
            name='max_mails_per_day',
            field=models.IntegerField(default=200),
        ),
    ]
