# Generated by Django 3.0.7 on 2020-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20200614_1816'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='matching_user_only_staff_or_participant',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('is_participant', False), ('is_staff', False), _connector='OR'), name='matching_user_only_staff_or_participant_or_none'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(is_participant=models.Q(('is_A', True), ('is_B', True), _connector='OR')), name='matching_user_only_participant_if_part_of_a_or_b'),
        ),
    ]
