# Generated by Django 3.0.7 on 2020-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_participantinfoa_participantinfob_participantinfolocationa_participantinfolocationb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantinfob',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='participantinfob',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participantinfob',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='participantinfob',
            name='pers_info--contact',
            field=models.CharField(default='AAA', max_length=100, verbose_name='Full name of the person to contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantinfob',
            name='pers_info--name',
            field=models.CharField(default='bbbb', max_length=100, verbose_name='Official name of your institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantinfob',
            name='pers_info--phone_number',
            field=models.CharField(default='dedede', max_length=100, verbose_name='Phone number of contact person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--accom',
            field=models.BooleanField(blank=True, default=False, verbose_name='I need accommodation'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--pref_area-ES',
            field=models.BooleanField(default=False, verbose_name='Emergency Services'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--pref_area-HO',
            field=models.BooleanField(default=False, verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--pref_area-LA',
            field=models.BooleanField(default=False, verbose_name='Laboratory'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--pref_area-ME',
            field=models.BooleanField(default=False, verbose_name='Medical Practice'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--pref_area-MP',
            field=models.BooleanField(default=False, verbose_name='Medical Practice'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--pref_area-NF',
            field=models.BooleanField(default=False, verbose_name='Nursing Facilities'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--pref_area-PD',
            field=models.BooleanField(default=False, verbose_name='Public Health Department and other Institutions'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--pref_area-PH',
            field=models.BooleanField(default=False, verbose_name='Pharmacy'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='info_supp--time_avail',
            field=models.IntegerField(choices=[(0, '10h per week'), (1, '20h per week'), (2, '30h per week'), (3, '40h per week')], verbose_name='Time Availability Per Week'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='pers_info--first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='pers_info--last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='pers_info--phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--area-AN',
            field=models.BooleanField(default=False, verbose_name='Anaestesiology'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--area-EM',
            field=models.BooleanField(default=False, verbose_name='Emergency Medicine'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--area-GM',
            field=models.BooleanField(default=False, verbose_name='General Medicine'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--area-IC',
            field=models.BooleanField(default=False, verbose_name='Intensive Care'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--area-IM',
            field=models.BooleanField(default=False, verbose_name='Internal Medicine'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--area-SU',
            field=models.BooleanField(default=False, verbose_name='Surgery'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--experience',
            field=models.IntegerField(blank=True, choices=[(0, 'Preclinical Section'), (1, 'Last Year Student'), (2, 'Assistant Doctor'), (3, 'Consultant')], default=0, null=True, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--internship',
            field=models.BooleanField(blank=True, default=False, verbose_name='Recognition as an internship or other study requirements is important'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud--other',
            field=models.CharField(max_length=500, verbose_name='Other Qualifications'),
        ),
        migrations.AlterField(
            model_name='participantinfoa',
            name='prof_train--medstud-cond',
            field=models.BooleanField(default=False, verbose_name='Medical Student / Doctor'),
        ),
    ]
