# Generated by Django 3.0.7 on 2020-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_match_participantinfoa_participantinfob_participantinfofiltera_participantinfofilterb_participantinf'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='response_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='response_subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
