# Generated by Django 3.0.7 on 2020-08-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_match_participantinfoa_participantinfob_participantinfofiltera_participantinfofilterb_participantinf'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--area-AN-exact',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--area-EM-exact',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--area-GM-exact',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--area-IC-exact',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--area-IM-exact',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--area-SU-exact',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--experience-gte',
            field=models.IntegerField(blank=True, choices=[(None, 'No choice'), (0, 'Preclinical Section'), (1, 'Last Year Student'), (2, 'Assistant Doctor'), (3, 'Consultant')], null=True),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--experience-lte',
            field=models.IntegerField(blank=True, choices=[(None, 'No choice'), (0, 'Preclinical Section'), (1, 'Last Year Student'), (2, 'Assistant Doctor'), (3, 'Consultant')], null=True),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--internship-exact',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='participantinfofiltera',
            name='prof_train--medstud--other-icontains',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
